<?xml version="1.0"?>
<package format="3">
  <name>ocp_constraint_body_contact</name>
  <version>0.0.0</version>
  <description>ocp_constraint_body_contact</description>

  <maintainer email="t-hiraoka@jsk.imi.i.u-tokyo.ac.jp">Takuma-Hiraoka</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ocp_solver</depend>
  <depend>assimp_eigen</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
